const USER_ROLES = {
    SUPER_ADMIN: "SUPER_ADMIN",
    MARKETING_ADMIN: "MARKETING_ADMIN",
    MERCHANT: "MERCHANT",
    VISITOR: "VISITOR"
}

const ALL = [USER_ROLES.SUPER_ADMIN, USER_ROLES.MARKETING_ADMIN, USER_ROLES.MERCHANT, USER_ROLES.VISITOR];
const ALL_AUTHORIZED = [USER_ROLES.SUPER_ADMIN, USER_ROLES.MARKETING_ADMIN, USER_ROLES.MERCHANT];
const ALL_ADMINS = [USER_ROLES.SUPER_ADMIN, USER_ROLES.MARKETING_ADMIN];

export { USER_ROLES, ALL, ALL_AUTHORIZED, ALL_ADMINS };